# Generated by Django 4.2.19 on 2025-03-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_listing_available_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={},
        ),
    ]
