# Generated by Django 4.2.19 on 2025-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_listing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="charger_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L1", "Level 1 (120V)"),
                    ("L2", "Level 2 (240V)"),
                    ("L3", "DC Fast Charging"),
                ],
                default="L2",
                max_length=10,
                verbose_name="EV Charger Level",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="connector_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("J1772", "J1772 (Standard)"),
                    ("CCS", "CCS (Combined Charging System)"),
                    ("CHAdeMO", "CHAdeMO"),
                    ("TESLA", "Tesla"),
                    ("TYPE2", "Type 2 (European)"),
                    ("OTHER", "Other"),
                ],
                default="J1772",
                max_length=10,
                verbose_name="EV Connector Type",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="has_ev_charger",
            field=models.BooleanField(default=False, verbose_name="Has EV Charger"),
        ),
    ]
