# Generated by Django 4.2.19 on 2025-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_charger_level_listing_connector_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='charger_level',
            field=models.CharField(blank=True, choices=[('L1', 'Level 1 (120V)'), ('L2', 'Level 2 (240V)'), ('L3', 'Level 3 (DC Fast Charging)')], default='L2', max_length=10, verbose_name='EV Charger Level'),
        ),
    ]
