# Generated by Django 4.2.19 on 2025-04-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_charger_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="parking_spot_size",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Size"),
                    ("COMPACT", "Compact"),
                    ("OVERSIZE", "Large/Oversize"),
                    ("COMMERCIAL", "Truck/Commercial"),
                ],
                default="STANDARD",
                max_length=15,
                verbose_name="Parking Spot Size",
            ),
        ),
    ]
