# Generated by Django 4.2.19 on 2025-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verification_file",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_documents/"
            ),
        ),
    ]
