# Generated by Django 4.2.19 on 2025-03-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
