# Generated by Django 4.2.19 on 2025-03-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0003_remove_booking_booking_date_remove_booking_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="no-email@example.com", max_length=254),
        ),
    ]
